# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'r_c.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 540)
        Form.setMinimumSize(QtCore.QSize(900, 540))
        Form.setMaximumSize(QtCore.QSize(900, 540))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 851, 391))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(678, 15, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(754, 42, 71, 331))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.formLayoutWidget_3.setFont(font)
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lineEdit30 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit30.setFont(font)
        self.lineEdit30.setText("")
        self.lineEdit30.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit30.setReadOnly(True)
        self.lineEdit30.setObjectName("lineEdit30")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit30)
        self.lineEdit31 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit31.setFont(font)
        self.lineEdit31.setText("")
        self.lineEdit31.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit31.setReadOnly(True)
        self.lineEdit31.setObjectName("lineEdit31")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit31)
        self.lineEdit32 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit32.setFont(font)
        self.lineEdit32.setText("")
        self.lineEdit32.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit32.setReadOnly(True)
        self.lineEdit32.setObjectName("lineEdit32")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit32)
        self.lineEdit33 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit33.setFont(font)
        self.lineEdit33.setText("")
        self.lineEdit33.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit33.setReadOnly(True)
        self.lineEdit33.setObjectName("lineEdit33")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit33)
        self.lineEdit34 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit34.setFont(font)
        self.lineEdit34.setText("")
        self.lineEdit34.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit34.setReadOnly(True)
        self.lineEdit34.setObjectName("lineEdit34")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit34)
        self.lineEdit35 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit35.setFont(font)
        self.lineEdit35.setText("")
        self.lineEdit35.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit35.setReadOnly(True)
        self.lineEdit35.setObjectName("lineEdit35")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit35)
        self.lineEdit36 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit36.setFont(font)
        self.lineEdit36.setText("")
        self.lineEdit36.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit36.setReadOnly(True)
        self.lineEdit36.setObjectName("lineEdit36")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit36)
        self.lineEdit37 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit37.setFont(font)
        self.lineEdit37.setText("")
        self.lineEdit37.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit37.setReadOnly(True)
        self.lineEdit37.setObjectName("lineEdit37")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit37)
        self.lineEdit38 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit38.setFont(font)
        self.lineEdit38.setText("")
        self.lineEdit38.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit38.setReadOnly(True)
        self.lineEdit38.setObjectName("lineEdit38")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit38)
        self.lineEdit39 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit39.setFont(font)
        self.lineEdit39.setText("")
        self.lineEdit39.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit39.setReadOnly(True)
        self.lineEdit39.setObjectName("lineEdit39")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit39)
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(36, 43, 181, 326))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.formLayoutWidget.setFont(font)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setText("")
        self.lineEdit2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit2.setObjectName("lineEdit2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit2)
        self.label9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label9)
        self.lineEdit8 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit8.setFont(font)
        self.lineEdit8.setText("")
        self.lineEdit8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit8.setObjectName("lineEdit8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit8)
        self.lineEdit5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setText("")
        self.lineEdit5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit5.setObjectName("lineEdit5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit5)
        self.lineEdit7 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit7.setFont(font)
        self.lineEdit7.setText("")
        self.lineEdit7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit7.setObjectName("lineEdit7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit7)
        self.label1 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.label3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label3)
        self.label5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label5)
        self.label8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label8.setFont(font)
        self.label8.setObjectName("label8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label8)
        self.lineEdit4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setText("")
        self.lineEdit4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit4.setObjectName("lineEdit4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit4)
        self.label7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label7)
        self.label2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.lineEdit3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setText("")
        self.lineEdit3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit3.setObjectName("lineEdit3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit3)
        self.lineEdit6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit6.setFont(font)
        self.lineEdit6.setText("")
        self.lineEdit6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit6.setObjectName("lineEdit6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit6)
        self.lineEdit1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setText("")
        self.lineEdit1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit1.setObjectName("lineEdit1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit1)
        self.label6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label6)
        self.label4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label4)
        self.lineEdit9 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit9.setFont(font)
        self.lineEdit9.setText("")
        self.lineEdit9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit9.setObjectName("lineEdit9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit9)
        self.lineEdit0 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit0.setFont(font)
        self.lineEdit0.setText("")
        self.lineEdit0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit0.setObjectName("lineEdit0")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit0)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(336, 76, 71, 293))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.formLayoutWidget_2.setFont(font)
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEdit21 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit21.setFont(font)
        self.lineEdit21.setText("")
        self.lineEdit21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit21.setReadOnly(True)
        self.lineEdit21.setObjectName("lineEdit21")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit21)
        self.lineEdit22 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit22.setFont(font)
        self.lineEdit22.setText("")
        self.lineEdit22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit22.setReadOnly(True)
        self.lineEdit22.setObjectName("lineEdit22")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit22)
        self.lineEdit23 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit23.setFont(font)
        self.lineEdit23.setText("")
        self.lineEdit23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit23.setReadOnly(True)
        self.lineEdit23.setObjectName("lineEdit23")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit23)
        self.lineEdit24 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit24.setFont(font)
        self.lineEdit24.setText("")
        self.lineEdit24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit24.setReadOnly(True)
        self.lineEdit24.setObjectName("lineEdit24")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit24)
        self.lineEdit25 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit25.setFont(font)
        self.lineEdit25.setText("")
        self.lineEdit25.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit25.setReadOnly(True)
        self.lineEdit25.setObjectName("lineEdit25")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit25)
        self.lineEdit26 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit26.setFont(font)
        self.lineEdit26.setText("")
        self.lineEdit26.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit26.setReadOnly(True)
        self.lineEdit26.setObjectName("lineEdit26")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit26)
        self.lineEdit27 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit27.setFont(font)
        self.lineEdit27.setText("")
        self.lineEdit27.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit27.setReadOnly(True)
        self.lineEdit27.setObjectName("lineEdit27")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit27)
        self.lineEdit28 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit28.setFont(font)
        self.lineEdit28.setText("")
        self.lineEdit28.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit28.setReadOnly(True)
        self.lineEdit28.setObjectName("lineEdit28")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit28)
        self.lineEdit29 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit29.setFont(font)
        self.lineEdit29.setText("")
        self.lineEdit29.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit29.setReadOnly(True)
        self.lineEdit29.setObjectName("lineEdit29")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit29)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(770, 15, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(354, 16, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(462, 42, 181, 353))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.formLayoutWidget_4.setFont(font)
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit10 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit10.setFont(font)
        self.lineEdit10.setText("")
        self.lineEdit10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit10.setObjectName("lineEdit10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit10)
        self.label1_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label1_2.setFont(font)
        self.label1_2.setObjectName("label1_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label1_2)
        self.lineEdit11 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit11.setFont(font)
        self.lineEdit11.setText("")
        self.lineEdit11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit11.setObjectName("lineEdit11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit11)
        self.label2_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label2_2.setFont(font)
        self.label2_2.setObjectName("label2_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label2_2)
        self.lineEdit12 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit12.setFont(font)
        self.lineEdit12.setText("")
        self.lineEdit12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit12.setObjectName("lineEdit12")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit12)
        self.label3_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label3_2.setFont(font)
        self.label3_2.setObjectName("label3_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label3_2)
        self.lineEdit13 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit13.setFont(font)
        self.lineEdit13.setText("")
        self.lineEdit13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit13.setObjectName("lineEdit13")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit13)
        self.label4_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label4_2.setFont(font)
        self.label4_2.setObjectName("label4_2")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label4_2)
        self.lineEdit14 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit14.setFont(font)
        self.lineEdit14.setText("")
        self.lineEdit14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit14.setObjectName("lineEdit14")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit14)
        self.label5_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label5_2.setFont(font)
        self.label5_2.setObjectName("label5_2")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label5_2)
        self.lineEdit15 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit15.setFont(font)
        self.lineEdit15.setText("")
        self.lineEdit15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit15.setObjectName("lineEdit15")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit15)
        self.label6_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label6_2.setFont(font)
        self.label6_2.setObjectName("label6_2")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label6_2)
        self.lineEdit16 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit16.setFont(font)
        self.lineEdit16.setText("")
        self.lineEdit16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit16.setObjectName("lineEdit16")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit16)
        self.label7_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label7_2.setFont(font)
        self.label7_2.setObjectName("label7_2")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label7_2)
        self.lineEdit17 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit17.setFont(font)
        self.lineEdit17.setText("")
        self.lineEdit17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit17.setObjectName("lineEdit17")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit17)
        self.label8_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label8_2.setFont(font)
        self.label8_2.setObjectName("label8_2")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label8_2)
        self.lineEdit18 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit18.setFont(font)
        self.lineEdit18.setText("")
        self.lineEdit18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit18.setObjectName("lineEdit18")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit18)
        self.label9_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label9_2.setFont(font)
        self.label9_2.setObjectName("label9_2")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label9_2)
        self.lineEdit19 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit19.setFont(font)
        self.lineEdit19.setText("")
        self.lineEdit19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit19.setObjectName("lineEdit19")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit19)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(121, 15, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(665, 42, 71, 331))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.formLayoutWidget_5.setFont(font)
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.lineEdit50 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit50.setFont(font)
        self.lineEdit50.setText("")
        self.lineEdit50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit50.setReadOnly(False)
        self.lineEdit50.setObjectName("lineEdit50")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit50)
        self.lineEdit51 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit51.setFont(font)
        self.lineEdit51.setText("")
        self.lineEdit51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit51.setReadOnly(False)
        self.lineEdit51.setObjectName("lineEdit51")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit51)
        self.lineEdit52 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit52.setFont(font)
        self.lineEdit52.setText("")
        self.lineEdit52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit52.setReadOnly(False)
        self.lineEdit52.setObjectName("lineEdit52")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit52)
        self.lineEdit53 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit53.setFont(font)
        self.lineEdit53.setText("")
        self.lineEdit53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit53.setReadOnly(False)
        self.lineEdit53.setObjectName("lineEdit53")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit53)
        self.lineEdit54 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit54.setFont(font)
        self.lineEdit54.setText("")
        self.lineEdit54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit54.setReadOnly(False)
        self.lineEdit54.setObjectName("lineEdit54")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit54)
        self.lineEdit55 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit55.setFont(font)
        self.lineEdit55.setText("")
        self.lineEdit55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit55.setReadOnly(False)
        self.lineEdit55.setObjectName("lineEdit55")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit55)
        self.lineEdit56 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit56.setFont(font)
        self.lineEdit56.setText("")
        self.lineEdit56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit56.setReadOnly(False)
        self.lineEdit56.setObjectName("lineEdit56")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit56)
        self.lineEdit57 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit57.setFont(font)
        self.lineEdit57.setText("")
        self.lineEdit57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit57.setReadOnly(False)
        self.lineEdit57.setObjectName("lineEdit57")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit57)
        self.lineEdit58 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit58.setFont(font)
        self.lineEdit58.setText("")
        self.lineEdit58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit58.setReadOnly(False)
        self.lineEdit58.setObjectName("lineEdit58")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit58)
        self.lineEdit59 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit59.setFont(font)
        self.lineEdit59.setText("")
        self.lineEdit59.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit59.setReadOnly(False)
        self.lineEdit59.setObjectName("lineEdit59")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit59)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(549, 15, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(252, 16, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(239, 43, 71, 331))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.formLayoutWidget_6.setFont(font)
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.lineEdit40 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit40.setFont(font)
        self.lineEdit40.setText("")
        self.lineEdit40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit40.setReadOnly(False)
        self.lineEdit40.setObjectName("lineEdit40")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit40)
        self.lineEdit41 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit41.setFont(font)
        self.lineEdit41.setText("")
        self.lineEdit41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit41.setReadOnly(False)
        self.lineEdit41.setObjectName("lineEdit41")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit41)
        self.lineEdit42 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit42.setFont(font)
        self.lineEdit42.setText("")
        self.lineEdit42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit42.setReadOnly(False)
        self.lineEdit42.setObjectName("lineEdit42")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit42)
        self.lineEdit43 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit43.setFont(font)
        self.lineEdit43.setText("")
        self.lineEdit43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit43.setReadOnly(False)
        self.lineEdit43.setObjectName("lineEdit43")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit43)
        self.lineEdit44 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit44.setFont(font)
        self.lineEdit44.setText("")
        self.lineEdit44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit44.setReadOnly(False)
        self.lineEdit44.setObjectName("lineEdit44")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit44)
        self.lineEdit45 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit45.setFont(font)
        self.lineEdit45.setText("")
        self.lineEdit45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit45.setReadOnly(False)
        self.lineEdit45.setObjectName("lineEdit45")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit45)
        self.lineEdit46 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit46.setFont(font)
        self.lineEdit46.setText("")
        self.lineEdit46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit46.setReadOnly(False)
        self.lineEdit46.setObjectName("lineEdit46")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit46)
        self.lineEdit47 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit47.setFont(font)
        self.lineEdit47.setText("")
        self.lineEdit47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit47.setReadOnly(False)
        self.lineEdit47.setObjectName("lineEdit47")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit47)
        self.lineEdit48 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit48.setFont(font)
        self.lineEdit48.setText("")
        self.lineEdit48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit48.setReadOnly(False)
        self.lineEdit48.setObjectName("lineEdit48")
        self.formLayout_8.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit48)
        self.lineEdit49 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit49.setFont(font)
        self.lineEdit49.setText("")
        self.lineEdit49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit49.setReadOnly(False)
        self.lineEdit49.setObjectName("lineEdit49")
        self.formLayout_8.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit49)
        self.lineEdit00 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit00.setGeometry(QtCore.QRect(343, 44, 63, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit00.setFont(font)
        self.lineEdit00.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit00.setReadOnly(True)
        self.lineEdit00.setObjectName("lineEdit00")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 17, 851, 71))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.use = QtWidgets.QPushButton(self.groupBox_2)
        self.use.setGeometry(QtCore.QRect(200, 17, 120, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.use.setFont(font)
        self.use.setObjectName("use")
        self.fac = QtWidgets.QPushButton(self.groupBox_2)
        self.fac.setGeometry(QtCore.QRect(372, 17, 120, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.fac.setFont(font)
        self.fac.setObjectName("fac")
        self.clear = QtWidgets.QPushButton(self.groupBox_2)
        self.clear.setGeometry(QtCore.QRect(540, 17, 120, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.open = QtWidgets.QPushButton(self.groupBox_2)
        self.open.setGeometry(QtCore.QRect(36, 17, 120, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.open.setFont(font)
        self.open.setObjectName("open")
        self.rec = QtWidgets.QPushButton(self.groupBox_2)
        self.rec.setGeometry(QtCore.QRect(701, 17, 120, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.rec.setFont(font)
        self.rec.setObjectName("rec")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(144, 93, 811, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(33, 93, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "灵敏度"))
        self.label9.setText(_translate("Form", "通道9"))
        self.label1.setText(_translate("Form", "通道1"))
        self.label3.setText(_translate("Form", "通道3"))
        self.label5.setText(_translate("Form", "通道5"))
        self.label8.setText(_translate("Form", "通道8"))
        self.label7.setText(_translate("Form", "通道7"))
        self.label2.setText(_translate("Form", "通道2"))
        self.label6.setText(_translate("Form", "通道6"))
        self.label4.setText(_translate("Form", "通道4"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#0055ff;\">标准器</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "结 论"))
        self.label_3.setText(_translate("Form", "结 论"))
        self.label_5.setText(_translate("Form", "通道10"))
        self.label1_2.setText(_translate("Form", "通道11"))
        self.label2_2.setText(_translate("Form", "通道12"))
        self.label3_2.setText(_translate("Form", "通道13"))
        self.label4_2.setText(_translate("Form", "通道14"))
        self.label5_2.setText(_translate("Form", "通道15"))
        self.label6_2.setText(_translate("Form", "通道16"))
        self.label7_2.setText(_translate("Form", "通道17"))
        self.label8_2.setText(_translate("Form", "通道18"))
        self.label9_2.setText(_translate("Form", "通道19"))
        self.label_7.setText(_translate("Form", "仪器编号"))
        self.label_8.setText(_translate("Form", "仪器编号"))
        self.label_9.setText(_translate("Form", "灵敏度"))
        self.lineEdit00.setText(_translate("Form", "无"))
        self.use.setText(_translate("Form", "使用中检定"))
        self.fac.setText(_translate("Form", "出厂检定"))
        self.clear.setText(_translate("Form", "清空数据"))
        self.open.setText(_translate("Form", "打开文件"))
        self.rec.setText(_translate("Form", "生成记录"))
        self.label_2.setText(_translate("Form", "1.填写仪器编号和灵敏度；2.点击打开文件；3.根据实际情点击使用中检定或出厂检定；4.生成检定记录"))
        self.label_10.setText(_translate("Form", "软件使用说明："))

